// Server - CovidBit
// Created: 03, February, 2021
// Teresa Costa - Fast Pandas

const bcrypt = require('bcrypt');
const jwt = require("jsonwebtoken")
const Administrator = require('../schema/user');


// Responsible for login query to database
// It only allows login for administrator for now
// Considering that validation is done on frontend
const loginUser = function (req, res) {
    //const { loginId, password } = req.body; // This is for frontend
    const { loginId, password } = req.query;  // Checks parameters from the request
    Administrator.findOne({ "loginId": loginId }, function (error, user) {
        if (error) throw error;
        if (!user) return res.status(400).json({ message: "I dont recognize you" });
        if (user) {
            bcrypt.compare(password, user.password, function (error, result) {
                console.log(password);
                console.log(user.password);
                if (error) throw error;
                if (!result) return res.status(400).json({ message: "Your password is incorrect" });
                const payload = {
                    user: {
                        id: user.id // id generated by mongodb, it will be delivery back to generate user dashboard
                    }
                };
                const token = jwt.sign(payload, "ilikemypandasfast", { expiresIn: 1000 });
                return res.status(200).json({ token });
            });
        }
    })
}

const returnUser = function (req, res) {
    Administrator.findById(req.user.id, function (error, administrator) {
        if (error) throw error;
        return res.status(200).json({ administrator })
    });
}

module.exports = { loginUser, returnUser };